version: 2
updates:
  # Fetch and update latest `nuget` pkgs
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - chore
      - dependency
      - nuget
    commit-message:
      prefix: chore
      include: scope

  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 10
    labels:
      - ci
      - dependency
      - github_actions
    commit-message:
      prefix: ci
      include: scope
