---
name: "Jellyfin Xtream"
guid: "5d774c35-8567-46d3-a950-9bb8227a0c5d"
version: "0.2.0.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "Stream content from an Xtream-compatible server."
description: >
  Stream Live IPTV, Video On-Demand, and Series from an Xtream-compatible server using this plugin.
category: "Live TV"
owner: "Kevinjil"
artifacts:
  - "Jellyfin.Xtream.dll"
changelog: >
  changelog
